spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.xjweykiymkvysrpsbwyk
    password: "DAb1239df0#!sd"

logging:
  level:
    org.unimelb: info
    com.baomidou.mybatisplus: warn
    org.apache.ibatis: warn