spring:
  datasource:
    url: jdbc:mysql://192.168.124.16:3306/plant_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: testDocker
    password: 123456

logging:
  level:
    org.unimelb: info
    com.baomidou.mybatisplus: warn
    org.apache.ibatis: warn